---
name: "YouTube Metadata 2 YouTube Horder"
guid: "e1204173-3802-4d53-980e-9d1b851fde84"
version: "1.1.1.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "JMiles42"
overview: "YouTube metadata provider"
description: |
  Provides YouTube metadata from the YouTube API and Youtube-dlp metadata files.
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.YoutubeMetadata.dll"
- "NYoutubeDLP.dll"
- "Newtonsoft.Json.dll"
- "System.IO.Abstractions.dll"
- "TestableIO.System.IO.Abstractions.dll"
- "TestableIO.System.IO.Abstractions.Wrappers.dll"
changelog: |
  improved finding local info.json files
